### ISSUE TITLE
Add certificate file path argument to configure_dynatrace_metrics_export function.

### ISSUE THREAD

**Issue by bercob** [dynatrace-oss/opentelemetry-metric-python#36]
To avoid SSL certificate issues I recommend to add certificate file path argument to configure_dynatrace_metrics_export function. This attribute will be used in requests methods, for example:

requests.get(url, verify=certificate_file)

**Comment by arminru** [comment]
Hi @bercob!
Could you please elaborate on what kind of certificate issues you're referring to here?
Do you mean self-signed certificates that are not trusted by the client by default, or do you want to pin a specific certificate to ensure the server is (still) the one you're expecting?

**Comment by bercob** [comment]
Hi @arminru, 
I mean to pin specific certificate. For example in initialisation of opentelemetry.exporter.otlp.proto.http.trace_exporter.OTLPSpanExporter it is possible by argument **certificate_file**.

**Comment by arminru** [comment]
I see, thanks.
The [`OTLPMetricExporter`](https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/metric_exporter/__init__.py) offered by OTel Python offers the same config argument actually.
Have you considered moving from this exporter package here to the generic OTel OTLP metrics exporter for Python?
Dynatrace supports ingesting OTLP metrics directly as well now. You can find more information here:

- https://www.dynatrace.com/support/help/shortlink/send-metrics-via-otlp-exporter
- https://www.dynatrace.com/support/help/shortlink/api-otlp-metrics-ingest
- https://www.dynatrace.com/support/help/shortlink/opent-python-metrics

**Comment by bercob** [comment]
Thanks for your advice. Another workaround is export the REQUESTS_CA_BUNDLE environment variable with the certificate file path.

**Comment by arminru** [comment]
This exporter has been deprecated in favor of the OTLP metrics ingest mentioned above and as such no new features will be implemented.

You can find a migration guide here, if you haven't upgraded yet:
https://docs.dynatrace.com/docs/shortlink/migrating-dynatrace-metrics-exporter-otlp-exporter
